### ISSUE TITLE
Missing glxserver_nvidia submodule?

### ISSUE THREAD

**Issue by dippynark** [squat/modulus#13]
I am trying to configure OpenGL 3D hardware acceleration - this project has got me very close, however there appears to be a missing sub module from my X Server log output.

Full details of this issue is on SO [here](https://stackoverflow.com/questions/61677116/how-to-compile-glxserver-nvidia-sub-module-on-coreos-for-opengl-3d-hardware-acce) - I can copy them here though if that'd be better.

**Comment by squat** [comment]
Hi @dippynark yeah could you share it here? that post seems to be deleted, plus it'll help future ppl :)

**Comment by dippynark** [comment]
@squat  Apologies, I just deleted it because I solved my problem straight after posting (typical) - the 3D X sever just couldn't find the library so have hacked the discovery togther with a symlink for now.

The library `libglxserver_nvidia.so` being discoverable was the key - thanks for the quick reply

**Comment by dippynark** [comment]
I think I just needed to remove the `--no-opengl-files` flag [here](https://github.com/squat/modulus/blob/89bfe3a82185e4ea809ab7811ec6b2ef6e6b48e5/nvidia/compile#L16) to make the library appear, although haven't checked whether that library existed already.

These are the commands I am running from within my 3D X Server (I'm sure there's a better way which I'll look for when everything else is working):
```
cp -a /usr/local/nvidia/lib/libglxserver_nvidia.so.440.82 /usr/lib/xorg/modules/extensions
ln -s /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so.440.82 /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so
```

**Comment by squat** [comment]
Ok I'm super glad you got it working :muscle:
