### ISSUE TITLE
DevicePlugin keeps Terminating

### ISSUE THREAD

**Issue by afritzler** [squat/modulus#4]
Hi,

I am facing a problem here with the DevicePlugin. It starts normally and the logs look fine. However after a couple of secs/mins the Pod gets terminated without any error. 

I am using your modulus daemonset and the latest GKE device plugin.

Any idea what is going on there? Is this the normal behaviour?

Thanks,
Andreas

**Comment by squat** [comment]
@afritzler which GKE device plugin configuration? the one in the Kubernetes addons repo? https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml can you share your configs?

**Comment by squat** [comment]
Looking through your repo, I see that you just bumped the tags in your configs a few hours ago [0]. I see that the device plugin version now differs from what's in master of the Kubernetes repo. I would advise you stay up to date with master. Nevertheless, I tested your config on my cluster and the device plugin pods are not restarting or crash-looping.

The NVIDIA driver installers do not directly interact with the device plugin; they are responsible for placing libraries on disk and creating NVIDIA device nodes which are then discovered by the device plugin. The only way that modulus could be causing your device plugin to fail could be if the libraries were not where you said they are or if the device nodes were not being created correctly. Even in both of those case, the device plugin should not crash but your GPU workloads would simply not work because the wrong directories are mounted in or the device plugin would not find any devices and your workloads would be unschedulable.

Some questions:
* are the drivers being installed correctly? can you try running the nvidia-smi utility?
* when you `kubectl describe node <your-node>` do any GPUs show up in the capacity/allocatable sections?
* can you share device plugin logs?
* are your GPU workloads running or pending?

[0] https://github.com/afritzler/kubernetes-gpu/commit/594523c3ab8776cdce3bb976f45b79e5f7432405

**Comment by afritzler** [comment]
The thing is, once modulus installs the drivers and the device plugin is initialised there is a short moment where I can launch my tensorflow deployment on this node. Inside the container everything looks fine. I can run nvidia-smi, TF training jobs etc. 

The device plugin logs (as long as it's running are looking fine - registering, detecting devices etc.)

Let me try to grab the logs from the host.

**Comment by afritzler** [comment]
This is how it looks like when the device plugin is started
```
I0524 09:13:07.628787       1 nvidia_gpu.go:40] device-plugin started
I0524 09:13:07.629407       1 manager.go:79] Found Nvidia GPU "nvidia0"
I0524 09:13:07.629497       1 manager.go:130] will use alpha API
I0524 09:13:07.629515       1 manager.go:144] starting device-plugin server at: /device-plugin/nvidiaGPU-1527153187.sock
I0524 09:13:07.629755       1 manager.go:173] device-plugin server started serving
I0524 09:13:07.630412       1 manager.go:177] falling back to v1beta1 API
I0524 09:13:07.726610       1 manager.go:185] device-plugin registered with the kubelet
I0524 09:13:07.726704       1 beta_plugin.go:38] device-plugin: ListAndWatch start
I0524 09:13:07.726734       1 beta_plugin.go:46] ListAndWatch: send devices &ListAndWatchResponse{Devices:[&Device{ID:nvidia0,Health:Healthy,}],```

**Comment by afritzler** [comment]
When I understood the device plugin framework correctly, this should be a process running permanently on the host?

**Comment by squat** [comment]
The device plugin should not be restarting constantly. This is definitely a bug. Can you post the result of:
```sh
kubectl describe pod <you-device-plugin-pod> -n kube-system
```
This may give insight into why your pod keeps getting restarted. Is your system running out of memory/cpu/resources?

If you revert your recent configuration changes is the device plugin once again stable? Essentially we need to know what is triggering this behavior.

You may have to file this bug with the Google Cloud Platform folks since this is their tool.

**Comment by afritzler** [comment]
Here is the output

```
Name:           nvidia-gpu-device-plugin-5794r
Namespace:      kube-system
Node:           ip-10-250-30-16.eu-west-1.compute.internal/10.250.30.16
Start Time:     Thu, 24 May 2018 13:51:44 +0200
Labels:         controller-revision-hash=148025000
                k8s-app=nvidia-gpu-device-plugin
                pod-template-generation=1
Annotations:    cni.projectcalico.org/podIP=100.96.1.20/32
                scheduler.alpha.kubernetes.io/critical-pod=
Status:         Running
IP:             100.96.1.20
Controlled By:  DaemonSet/nvidia-gpu-device-plugin
Containers:
  nvidia-gpu-device-plugin:
    Container ID:  docker://dbd138c4e538dd6fb0251d37858963570a85e86529e8c2afed941904b0367c7b
    Image:         k8s.gcr.io/nvidia-gpu-device-plugin@sha256:0842734032018be107fa2490c98156992911e3e1f2a21e059ff0105b07dd8e9e
    Image ID:      docker-pullable://k8s.gcr.io/nvidia-gpu-device-plugin@sha256:0842734032018be107fa2490c98156992911e3e1f2a21e059ff0105b07dd8e9e
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/nvidia-gpu-device-plugin
      -logtostderr
      -host-path=/opt/drivers/nvidia
    State:          Running
      Started:      Thu, 24 May 2018 13:51:46 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  10Mi
    Requests:
      cpu:        50m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /dev from dev (rw)
      /device-plugin from device-plugin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-f92dj (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:
  default-token-f92dj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-f92dj
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     :NoExecute
                 :NoSchedule
                 :NoExecute
                 :NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:
  Type    Reason                 Age        From                                                 Message
  ----    ------                 ----       ----                                                 -------
  Normal  SuccessfulMountVolume  <invalid>  kubelet, ip-10-250-30-16.eu-west-1.compute.internal  MountVolume.SetUp succeeded for volume "device-plugin"
  Normal  SuccessfulMountVolume  <invalid>  kubelet, ip-10-250-30-16.eu-west-1.compute.internal  MountVolume.SetUp succeeded for volume "dev"
  Normal  SuccessfulMountVolume  <invalid>  kubelet, ip-10-250-30-16.eu-west-1.compute.internal  MountVolume.SetUp succeeded for volume "default-token-f92dj"
  Normal  Pulled                 <invalid>  kubelet, ip-10-250-30-16.eu-west-1.compute.internal  Container image "k8s.gcr.io/nvidia-gpu-device-plugin@sha256:0842734032018be107fa2490c98156992911e3e1f2a21e059ff0105b07dd8e9e" already present on machine
  Normal  Created                <invalid>  kubelet, ip-10-250-30-16.eu-west-1.compute.internal  Created container
  Normal  Started                <invalid>  kubelet, ip-10-250-30-16.eu-west-1.compute.internal  Started container
```

**Comment by afritzler** [comment]
In the kubelet logs I found this 
```
kubelet_pods.go:1121] Killing unwanted pod "nvidia-gpu-device-plugin-btrpv"
```

**Comment by squat** [comment]
Interesting. Looks like something is causing the pod to not be scheduled to your node. You may need to pull scheduler and controller-manager logs as well. This is confirming the theory that this issue particular to your cluster configuration and unrelated to modulus.

**Comment by afritzler** [comment]
So removing `addonmanager.kubernetes.io/mode: Reconcile` from the labels seems to have solved the problem.

**Comment by afritzler** [comment]
Btw. I just had a look on what the init container is doing during installation:
```
Creating directory NVIDIA-Linux-x86_64-390.48
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 390.48........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
/tmp/nvidia/NVIDIA-Linux-x86_64-390.48 /tmp/nvidia /

WARNING: nvidia-installer was forced to guess the X library path '/usr/lib'
         and X module path '/usr/lib/xorg/modules'; these paths were not
         queryable from the system.  If X fails to find the NVIDIA X driver
         module, please install the `pkg-config` utility and the X.Org
         SDK/development package for your distribution and reinstall the
         driver.


WARNING: Unable to find a suitable destination to install 32-bit
         compatibility libraries. Your system may not be set up for 32-bit
         compatibility. 32-bit compatibility files will not be installed;
         if you wish to install them, re-run the installation and set a
         valid directory with the --compat32-libdir option.


ERROR: Unable to load the 'nvidia-drm' kernel module.


ERROR: Installation has failed.  Please see the file
       '/tmp/nvidia/NVIDIA-Linux-x86_64-390.48/nvidia-installer.log' for
       details.  You may find suggestions on fixing installation problems
       in the README available on the Linux driver download page at
       www.nvidia.com.

Successfully compiled NVIDIA modules
Archiving assets
depmod: WARNING: could not open /opt/drivers/nvidia/lib/modules/4.14.42-coreos/modules.order: No such file or directory
depmod: WARNING: could not open /opt/drivers/nvidia/lib/modules/4.14.42-coreos/modules.builtin: No such file or directory
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/opt/drivers/nvidia/lib/modules/4.14.42-coreos/modules.builtin.bin'
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/opt/drivers/nvidia/lib/modules/4.14.42-coreos/modules.builtin.bin'
```
Looks kinda odd, however if I do an `lsmod`:
```
nvidia_drm             16384  0
nvidia_modeset       1110016  0
nvidia_uvm            860160  0
nvidia              14372864  8 nvidia_modeset,nvidia_uvm
```
things look fine. I can also run a TF container on top without a problem.

**Comment by afritzler** [comment]
Ok, so after removing the addon label things seem to work now. Device plugin is not killed + node capacity + allocatable is correctly updated by the kubelet.

I think we can close this one.

**Comment by squat** [comment]
I am glad you figured it out. The addon manager can produce unintuitive results, e.g. when you update manifests in the API but not on disk.

```
ERROR: Unable to load the 'nvidia-drm' kernel module.
```
This is likely some conflict with the BIOS settings on the machine, e.g. secure boot is enabled. These errors are ignored since the rest of the drivers still work so if you do not need DRM then everything else works. Future work is cleaning up the noisy depmod/modprobe output.

Closing for now, @afritzler.

**Comment by afritzler** [comment]
Thanks a lot again! I will open an issue regarding the addon label in the GKE repo.
