### ISSUE TITLE
Systemd instructions now fail when compiling Nvidia

### ISSUE THREAD

**Issue by AnalogJ** [squat/modulus#9]
Hey,
The systemd instructions now fail in the complication stage (`systemct start ..`) after your most recent change. 

I ended up just using a previous commit to get everything working, and unfortunately I don't have the failing log files available to include in this issue.

**Comment by squat** [comment]
@AnalogJ sorry for the delay, I think this is now fixed as of https://github.com/squat/modulus/commit/ea768e4f10ddfaac083f1972a7e2278afa4fad6c. I have tested on a few machines and it all seems to be working for me :tm: 
Please give master a shot :)

**Comment by squat** [comment]
I’ll close this for now, but please reopen if you still see the issue :)
